### ISSUE TITLE
Unable to query Flight: Table 'tpch.customer' not found...

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#1583]
**Describe the bug**
An error is returned from running `tpch_q13` (and others, see below) against the Spice Cloud system with the following message:

`Error: "query tpch_q13 to results: External error: Execution error: Unable to query Flight: Unable to query: status: InvalidArgument, message: \"Table 'tpch.customer' not found ...`

**To Reproduce**
Uncomment `tpch_q13` from the benchmark tests and run.

This affects the following benchmark queries:

- `tpch_q13`
- `tpch_q16`
- `tpch_simple_q3`

This may be related to #1581

Edit:

- tpch_q13 is passing now. 
- tpch_q16 is failing due to a DBMS issue which unable to use  clause like`where a.b.c > 1`, but `where b.c > 1` works. Copy the generated tpch_q16 query works in athena. So it might not need a fix for spice.ai connector.
- raised the #2000 instead for tpch_simple_q3 which is different issue than tpch_q13. Will track the info there.

**Comment by edmondop** [comment]
Still failing, will probably require another PR on https://github.com/spiceai/datafusion-federation

**Comment by y-f-u** [comment]
Close this issue.

> tpch_q13 is passing now.
tpch_q16 is failing due to a DBMS issue which unable to use clause likewhere a.b.c > 1, but where b.c > 1 works. Copy the generated tpch_q16 query works in athena. So it might not need a fix for spice.ai connector.
raised the
https://github.com/spiceai/spiceai/issues/2000 instead for tpch_simple_q3 which is different issue than tpch_q13. Will track the info there.
