### ISSUE TITLE
Postgres data connector crashes on types: Json, Point, Money

### ISSUE THREAD

**Issue by digadeesh** [spiceai/spiceai#1771]
**Describe the bug**
Postgres data connector crashes on types: Json, Point, Money: 
thread 'main' panicked at crates/arrow_sql_gen/src/postgres.rs:517:14:

not implemented: Unsupported column type Json
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace

**To Reproduce**
Connect to a Postgres database with a table configured with the fields above

**Expected behavior**
Database is queryable.  If not supported, the database should not crash.

**Comment by hcrypto7** [comment]
I will solve this problem.

**Comment by phungleson** [comment]
Hey @hcrypto7  I was looking into this before seeing your comment, anyway a few thoughts regarding the issue:

First, `clickhouse` and `mysql` also have the similar issue so perhaps we should fix them as well? or make this into smaller issues/PRs.

https://github.com/spiceai/spiceai/blob/50733d0b524ef4aec33f2d7a328acc901fd2be2c/crates/arrow_sql_gen/src/clickhouse.rs#L530-L532

https://github.com/spiceai/spiceai/blob/50733d0b524ef4aec33f2d7a328acc901fd2be2c/crates/arrow_sql_gen/src/mysql.rs#L465-L467

https://github.com/spiceai/spiceai/blob/50733d0b524ef4aec33f2d7a328acc901fd2be2c/crates/arrow_sql_gen/src/mysql.rs#L411-L413

Second, `clickhouse` has a snafu error for this kind of problem so maybe we should do something similar to that?

https://github.com/spiceai/spiceai/blob/50733d0b524ef4aec33f2d7a328acc901fd2be2c/crates/arrow_sql_gen/src/clickhouse.rs#L77-L79

Last, `postgres` implementation has a tricky case for `NUMERIC` so keep it in mind if you want to refactor the code.

https://github.com/spiceai/spiceai/blob/50733d0b524ef4aec33f2d7a328acc901fd2be2c/crates/arrow_sql_gen/src/postgres.rs#L569-L570

**Comment by hcrypto7** [comment]
I think it's a good idea to make it a smaller issue/PR.

**Comment by phillipleblanc** [comment]
FYI the Postgres/MySQL Table Providers were moved to https://github.com/datafusion-contrib/datafusion-table-providers, so they will need to be fixed there first.

**Comment by phillipleblanc** [comment]
@hcrypto7 - How are you coming along on this?

**Comment by Sevenannn** [comment]
Fix Json type in datafusion table providers:https://github.com/datafusion-contrib/datafusion-table-providers/pull/40
Postgres:
![Image](https://github.com/user-attachments/assets/2c8b68f6-858d-4cc8-9fdc-e9edd595b085)
Spice:
![Image](https://github.com/user-attachments/assets/b42fa7c1-d2e5-4758-9a2a-4ad2019fa696)

**Comment by Sevenannn** [comment]
Fix Point type in datafusion table providers: https://github.com/datafusion-contrib/datafusion-table-providers/pull/49
Postgres:
![Image](https://github.com/user-attachments/assets/a642de89-d87c-4858-9271-a2f1e1dcd035)
Spice:
![Image](https://github.com/user-attachments/assets/999a2ec3-bc0d-4fe0-be38-3287f50dfe58)

**Comment by Sevenannn** [comment]
Fix Money Type in datafusion table providers: https://github.com/datafusion-contrib/datafusion-table-providers/pull/50
Since there's no arrow data type of money, while postgres Money is sent as an i64 of the lowest denomination of money in the [underlying bindings](https://github.com/postgres/postgres/blob/bd8fe12ef3f727ed3658daf9b26beaf2b891e9bc/src/backend/utils/adt/cash.c#L603). The money will be converted into lowest denomination in i64, and stored in arrow i64 array, to ensure the integrity of the actual cash value.
Examples:
* USD(cent)
  * Postrges
![Image](https://github.com/user-attachments/assets/bc8b541c-7bfc-44d5-9213-d65196c88934)
  * Spice
![Image](https://github.com/user-attachments/assets/1facb59b-6c99-4e59-956a-a0f330531552)
* CNY(cent)
  * Postrges
![Image](https://github.com/user-attachments/assets/8cc13466-867e-4ea0-90b0-d4b9d130fee8)
  * Spice
![Image](https://github.com/user-attachments/assets/99368712-5657-43a1-ac54-da06e332c738)
* JPY(yen)
  * Postrges
![Image](https://github.com/user-attachments/assets/670ac4ac-41fa-451b-9630-8044848866f2)
  * Spice
![Image](https://github.com/user-attachments/assets/696bc76f-de90-49e1-bab4-05af78f0ae0d)
