### ISSUE TITLE
SQL REPL error output should be improved

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#2018]
**Describe the bug**
We should not show internal errors for user errors or parsing errors.

i.e.

`SELECT * FROM non_existing_table` will produce an internal error when connected to a Spice.ai dataset:

`Status { code: Internal, message: "External error: Execution error: Unable to query Flight: Unable to query: status: InvalidArgument, message: \"Table 'tpch.orders' not found\\nstartLine 1\\nstartColumn 413\\nendLine 1\\nendColumn 423\\nSQL Query SELECT b.o_orderkey, b.o_custkey, b.o_orderstatus, b.o_totalprice, b.o_orderdate, b.o_orderpriority, b.o_clerk, b.o_shippriority, b.o_comment FROM (SELECT tpch.orders.o_orderkey, tpch.orders.o_custkey, tpch.orders.o_orderstatus, tpch.orders.o_totalprice, tpch.orders.o_orderdate, tpch.orders.o_orderpriority, tpch.orders.o_clerk, tpch.orders.o_shippriority, tpch.orders.o_comment FROM tpch.orders) AS b ORDER BY tpch.orders.o_orderkey ASC NULLS LAST LIMIT 1\", details: [], metadata: MetadataMap { headers: {\"date\": \"Fri, 19 Jul 2024 00:02:58 GMT\", \"content-type\": \"application/grpc\", \"strict-transport-security\": \"max-age=15724800; includeSubDomains\", \"alt-svc\": \"h3=\\\":443\\\"; ma=86400\", \"cf-ray\": \"8a567217ebe55a9c-MEL\", \"cf-cache-status\": \"DYNAMIC\", \"server\": \"cloudflare\"} }", source: None }`

**To Reproduce**

**Expected behavior**

**Spicepod**
Add the relevant `spicepod.yml` section.

**Output of the `describe table`**
Add any relevant `describe table` output here.

**Output of `explain query`**
Add any relevant `explain query` output here.

E.g. `explain select 1`
```
+---------------+--------------------------------------+
| plan_type     | plan                                 |
+---------------+--------------------------------------+
| logical_plan  | Projection: Int64(1)                 |
|               |   EmptyRelation                      |
| physical_plan | ProjectionExec: expr=[1 as Int64(1)] |
|               |   PlaceholderRowExec                 |
|               |                                      |
+---------------+--------------------------------------+
```

**spice, spiced, OS info**
- spice version: `spice version`
- spiced version: `spiced --version`
- OS info: `uname -a`

**Have you tried this on the latest `trunk` branch?**

**If possible, run `spiced` with DEBUG log level**

By setting the environment variable `SPICED_LOG="spiced=DEBUG,runtime=DEBUG,data_components=DEBUG,cache=DEBUG"`

**Screenshots**

**Additional context**

**Comment by Sevenannn** [comment]
As confirmed Jul 29th, `SELECT * FROM non_existing_table` don't produce internal error. However, similar error is found when exeuting failing queries (e.g. tpch_q4)

```
sql> SELECT * FROM non_existing_table
Query Error table 'spice.public.non_existing_table' not found
```

**To Reproduce**

1. Configure spicepod as followings, run `spice run`
2. In separate terminal, run `spice sql`
3. run [tpch_q4](https://github.com/spiceai/spiceai/blob/356df9df9bce5a187ae47f98a40b814af68d2f5c/crates/runtime/benches/queries/tpch_q4.sql#L4) in spice sql repl
4. See error using `.error`
`
Status { code: Internal, message: "External error: Execution error: Unable to query Arrow Flight: Unable to query: status: InvalidArgument, message: \"Table 'tpch.lineitem' not found\\nstartLine 1\\nstartColumn 722\\nendLine 1\\nendColumn 734\\nSQL Query SELECT tpch.orders.o_orderpriority, count(1) AS order_count FROM tpch.orders WHERE (((tpch.orders.o_orderdate >= CAST('1993-07-01' AS TIMESTAMP)) AND (tpch.orders.o_orderdate < CAST((CAST('1993-07-01' AS DATE) + INTERVAL '3' MONTH) AS TIMESTAMP))) AND EXISTS (SELECT tpch.lineitem.l_orderkey, tpch.lineitem.l_partkey, tpch.lineitem.l_suppkey, tpch.lineitem.l_linenumber, tpch.lineitem.l_quantity, tpch.lineitem.l_extendedprice, tpch.lineitem.l_discount, tpch.lineitem.l_tax, tpch.lineitem.l_returnflag, tpch.lineitem.l_linestatus, tpch.lineitem.l_shipdate, tpch.lineitem.l_commitdate, tpch.lineitem.l_receiptdate, tpch.lineitem.l_shipinstruct, tpch.lineitem.l_shipmode, tpch.lineitem.l_comment FROM tpch.lineitem WHERE ((tpch.lineitem.l_orderkey = tpch.orders.o_orderkey) AND (tpch.lineitem.l_commitdate < tpch.lineitem.l_receiptdate)))) GROUP BY tpch.orders.o_orderpriority ORDER BY tpch.orders.o_orderpriority ASC NULLS LAST\", details: [], metadata: MetadataMap { headers: {\"date\": \"Tue, 30 Jul 2024 04:51:46 GMT\", \"content-type\": \"application/grpc\", \"strict-transport-security\": \"max-age=15724800; includeSubDomains\", \"alt-svc\": \"h3=\\\":443\\\"; ma=86400\", \"cf-ray\": \"8ab2bc48bad76826-SEA\", \"cf-cache-status\": \"DYNAMIC\", \"server\": \"cloudflare\"} }", source: None }
`

**Expected behavior**
A clear and concise description of what you expected to happen.

**Spicepod**
```
version: v1beta1
kind: Spicepod
name: spark_demo
datasets:
  - from: spice.ai/tpch.supplier
    name: supplier
  - from: spice.ai/tpch.part
    name: part
  - from: spice.ai/tpch.customer
    name: customer
  - from: spice.ai/tpch.orders
    name: orders
  - from: spice.ai/tpch.nation
    name: nation
  - from: spice.ai/tpch.partsupp
    name: partsupp
  - from: spice.ai/tpch.lineitem
    name: lineitem
  - from: spice.ai/tpch.region
    name: region

```
