### ISSUE TITLE
Enhancement: Postgres Accelerator can load and run TPCDS queries 

### ISSUE THREAD

**Issue by Sevenannn** [spiceai/spiceai#2550]
## Goal-State/What/Result

Postgres Accelerator can support TPCDS workloads

## By When

A target date for done-done completion of the entire enhancement.

**Issue/Spec written and reviewed:** <Target Date>
**Done-Done:** 11th October, 2024

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] ~PM/Design Review~ (not applicable)
- [x] ~UX Review~ (not applicable)
- [x] Threat Model / Security Review
- [x] Tests
- [x] Documentation
- [x] ~Samples/Quickstarts/Tutorials~ (not applicable)
- [x] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Spec

Basic specification of the enhancement.

## How/MAP

A clear and concise plan of how this should be implemented.

### Implementation (issues)

- 
-

**Comment by phillipleblanc** [comment]
Should also re-enable the sub-test in `acceleration_with_and_without_federation`

**Comment by sgrebnov** [comment]
Status as of 09/14: @Sevenannn has run the TPCDS queries and reported new bugs, but we have not started working on them.

**Comment by phillipleblanc** [comment]
Outcome: Done-Done this week

**Comment by sgrebnov** [comment]
https://github.com/spiceai/spiceai/issues?q=is%3Aissue%20tpcds%20label%3Aarea%2Fdata-accelerators%20is%3Aopen%20%20%20

**Comment by sgrebnov** [comment]
| Bug | Impact | Notes |
|--------|--------|--------|
| ~[Query Error function round(double precision, integer) does not exist](https://github.com/spiceai/spiceai/issues/2844)~ | High | [Fix available](https://github.com/spiceai/datafusion/pull/34). Unparser issue, high as there is no workaround that blocks usage of `round` fn |
| ~[Schema mismatch: Query returned an unexpected data type for column sales_before: expected Decimal128(18, 2), received Decimal128(33, 2)](https://github.com/spiceai/spiceai/issues/2696)~ | High | [Fix available](https://github.com/spiceai/datafusion/pull/33). High as there is no workaround preventing to use `coalesce` function. Datafusion core issue (incorrect UDF type returned)
| ~[Tried to unproject agg expr not found in provided Aggregate](https://github.com/spiceai/spiceai/issues/2650)~ | High | [Fix available](https://github.com/spiceai/datafusion/pull/35). Unparser issue, does not support combination of Window and Aggregation. No workaround exist|
|~[Query Error Join Error](https://github.com/spiceai/spiceai/issues/2648)~|High| Fixed. Several queries affected, unparser crashes|
|~[Query Error Unable to query arrow: db error: ERROR: missing FROM-clause entry for table "x ](https://github.com/spiceai/spiceai/issues/2706) && [Bug: TPCDS error Could not ORDER BY column .. move the UNION into a FROM clause](https://github.com/spiceai/spiceai/issues/2963)~| High | Blocks using complex UNION queries, Datafusion creates invalid plan for union and return incorrect result - grouping is incorrect |
| ~[ERROR: syntax error at or near "ANTI"](https://github.com/spiceai/spiceai/issues/2707)~  |Low/Medium | Unparser issue producing unsupported statement `AntiJoin`. The same query can be rewritten. AI: document |
|~[syntax error at or near "SEMI](https://github.com/spiceai/spiceai/issues/2649)~|Low/Medium | Unparser issue producing unsupported statement `Semioin`. The same query can be rewritten. AI: document
| ~[Projections require unique expression names](https://github.com/spiceai/spiceai/issues/2705)~ | Low | Datafusion limitation, two columns with the same name are selected. Easy workaround by adding AS / aliasing. AI: document  | 
|~[Cannot coerce arithmetic expression Date32 + Int64 to valid types](https://github.com/spiceai/spiceai/issues/2623)~ |Low| Datafusion limitation, documented |
| ~[The context currently only supports a single SQL statement](https://github.com/spiceai/spiceai/issues/2617)~ | Low | No support for multiple queries, easy workaround for users, documented. |
| ~[Query Error Expected: ), found: days](https://github.com/spiceai/spiceai/issues/2610)~  | Low | Query contains invalid Postgres syntax, that should be updated and documented (done), easy workaround for users |
| ~[column "count(DISTINCT cs1.cs_order_number)" does not exist](https://github.com/spiceai/spiceai/issues/2699)~ | Medium  | Fixed | 
|~[column my_customers.c_customer_sk does not exist](https://github.com/spiceai/spiceai/issues/2704)~ | Duplicate(?) | Seems to be a duplicate / same issue cause as  https://github.com/spiceai/spiceai/issues/2963|
| ~[Internal error: Failed to build right relation](https://github.com/spiceai/spiceai/issues/2647)~| Duplicate(?) | Seems to be a duplicate / same issue cause as  https://github.com/spiceai/spiceai/issues/2963|
|~[Bug: TPCDS error Values list "ssr" does not have a column named "s_store_id"](https://github.com/spiceai/spiceai/issues/2966)~ | Duplicate(?) | Seems to be a duplicate / same issue cause as  https://github.com/spiceai/spiceai/issues/2963|
|~[Bug: TPCDS error Referenced column "sum(store_sales.ss_net_profit)" not found](https://github.com/spiceai/spiceai/issues/2965)~ | Medium | ORDER BY unparsing issue - not fully unparsed |
|~[Bug: TPCDS error Referenced column "substr(reason.r_reason_desc,Int64(1),Int64(20))" not found](https://github.com/spiceai/spiceai/issues/2962)~ | Medium | Unparser does not correctly handle scalar functions in ORDER BY if the same calculation exists in FROM / projection.  |
|~[Bug: TPCDS error Referenced column "grouping(item.i_category)" not found in FROM clause](https://github.com/spiceai/spiceai/issues/2961)~ | Medium | Unparser issue|
| ~[Postgres Accelerator TPCDS Error: Query Error Unable to query arrow: db error: ERROR: division by zero](https://github.com/spiceai/spiceai/issues/2708)~ | Invalid Query / Data | There is `Execution error: Unable to query arrow: db error: ERROR: division by zero` error in Postgres due to filter does not correspond to generated data

**Comment by sgrebnov** [comment]
**Target outcome for this week: done-done**

Passing rate increased from 40% to 70%, there are still ~4 issues to address. ETA to complete - Wed 10/09

**Comment by sgrebnov** [comment]
✅ Completed:

- Passing rate increased from 70% to 89%,  Remaining work: investigate/fix ~[Postgres Accelerator TPCDS Error: Query Error Unable to query arrow: db error: ERROR: division by zero](https://github.com/spiceai/spiceai/issues/2708)~ done
- All failed queries are covered by documented limitations: https://github.com/spiceai/spiceai/blob/trunk/crates/runtime/benches/queries/README.md
