### ISSUE TITLE
S3 data connector hardening

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#2562]
1. Ensure quality of s3/(parquet|json|csv). Push-down, etc.
2. Add missing tests for core functionality (if any)
3. Document effective usage of s3/(parquet|json|csv)
4. Update error message when client_timeout is reached

Current error message isn't very helpful:
![Image](https://github.com/user-attachments/assets/9d159062-711b-4d1b-95b4-4249abb68455)

5. Add version of file that was access for the refresh when bucket versioning is enabled.

**Comment by sgrebnov** [comment]
Have not started working on this. Won't be completed by 0.18.0-beta release

**Comment by phillipleblanc** [comment]
Push down of `LIMIT` wasn't happening due to https://github.com/spiceai/spiceai/pull/2867, although in testing this didn't seem to change the number of bytes that it ended up scanning for `taxi_trips`.

However, I did find that in `taxi_trips` (`s3://spiceai-demo-datasets/taxi_trips/2024/`) the number of bytes it scanned was always constant (the whole file). It also didn't seem to respect any filters that were applied. I double checked that the `ParquetExec` from DataFusion was doing the right thing, and it seemed to be.
I then checked the metadata of the `taxi_trips` file and found the problem. Parquet encodes statistics about each column in each row groups (i.e. min/max, nulls, distinct count), and DataFusion uses that for efficient filter pruning. However, its optional and if the file itself doesn't contain those statistics, then there isn't much DataFusion (or any query engine) can do. The `taxi_trips` parquet file doesn't have any statistics, so it has to read the entire file everytime it does any query.

**Comment by phillipleblanc** [comment]
I re-uploaded the `taxi_trips` dataset in S3 sorted by `passenger_count` and adding a refresh_sql for `SELECT * FROM taxi_trips WHERE passenger_count = 2` is noticeably faster than loading all data:

```bash
2024-10-07T22:17:08.839567Z  INFO runtime::accelerated_table::refresh_task: Loaded 2,964,624 rows (398.86 MiB) for dataset taxi_trips in 7s 444ms.
2024-10-07T22:17:21.257664Z  INFO runtime: Updating accelerated dataset taxi_trips...
2024-10-07T22:17:21.713384Z  INFO runtime::accelerated_table::refresh_task: Loading data for dataset taxi_trips
2024-10-07T22:17:23.536684Z  INFO runtime::accelerated_table::refresh_task: Loaded 405,103 rows (54.48 MiB) for dataset taxi_trips in 1s 823ms.
2024-10-07T22:17:23.886582Z  INFO runtime: Dataset taxi_trips registered (s3://spiceai-demo-datasets/taxi_trips/2024/), acceleration (arrow), results cache enabled.
```

**Comment by phillipleblanc** [comment]
Closing in favor of #3224
