### ISSUE TITLE
Error message with invalid s3 endpoint contains S3 XML response

### ISSUE THREAD

**Issue by digadeesh** [spiceai/spiceai#954]
**Describe the bug**

**To Reproduce**
configure S3 dataset with an invalid url

Notice the error in the runtime:

Failed to initialize data connector for dataset taxi_trips, retrying: Unable to attach data connector s3: Unable to register table: Unable to get table provider: Object Store error: Generic S3 error: Error performing list request: Client error with status 404 Not Found: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>sdadsspiceai-demo-datasets</BucketName><RequestId>H26MK4F7YK9TZG8H</RequestId><HostId>K2b90aqpw9Gk9+47gs2SZN1RXp4vyxSUUK79yLSsJ12STOMW2FJ0D8Ue6Ypnt+5BWiUDHic5bx4=</HostId></Error>

**Expected behavior**
A friendly error like "bucket not found"

**Screenshots**

**Additional context**

**Comment by digadeesh** [comment]
Test with other data sources.  May not be only S3.

**Comment by Sevenannn** [comment]
Took a look at this error, the following error message comes from the external crate `object_store::Error`
```
Object Store error: Generic S3 error: Error performing list request: Client error with status 404 Not Found: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>spiceai-demo-dasets</BucketName><RequestId>KKRANQBKFVFT6N29</RequestId><HostId>b04xFbzkBD8zJ5OBFXiQqynhXExUX4iAZW8+ToCcz9nR4FWO1JkKGoV08EyZBlf/R2bkj++8p4w=</HostId></Error>
```
The best solution here is submitting a error message fixing ticket in object store crate. Since the function we are calling could cause `object_store::Error` other than the one demonstrated above, whose levels of sources vary. It wouldn't be reasonable to unnest and handle the `object_store::Error` from Spice codebase, because we are unable to guess the which error would arise and how we make a better error message it accordingly.

**Comment by Sevenannn** [comment]
- Close by https://github.com/spiceai/spiceai/issues/1229
